name: astropy_rc_basic

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

# These only prove that basic test suite in Linux works.
# It is up to the individual packages to do detailed testing with astropy RC.
jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      submodules: false
      toxdeps: "'tox<4'"
      envs: |
        - linux: py310-asdf_astropy
        - linux: py310-astropy_healpix
        - linux: py310-astroquery
        - linux: py310-ccdproc
        - linux: py310-photutils
        - linux: py310-regions
        - linux: py310-reproject
        - linux: py310-specreduce
        - linux: py310-specutils
        - linux: py310-sunpy
